### ISSUE TITLE
Invalid Shapefile version

### ISSUE THREAD

**Issue by hol430** [SharpMap/SharpMap#188]
Hi, I've just tried to create a sample app which starts by reading in a shapefile. I have a shapefile which I think I downloaded from a matplotlib tutorial somewhere but when I try to open it using this library I get the below error. I notice that this exception is triggered when the version (bytes 28-31) are not equal to 1000 (0x03e8), but in my file I have 0xe803. Is this a bug, or do I just have a dodgy shapefile? Or I have some other misunderstanding?

```
System.ApplicationException: Invalid Shapefile version
   at SharpMap.Data.Providers.ShapeFileHeader..ctor(BinaryReader headerReader)
   at SharpMap.Data.Providers.ShapeFileHeader..ctor(Stream header)
   at SharpMap.Data.Providers.ShapeFileHeader..ctor(Byte[] header)
   at SharpMap.Data.Providers.ShapeFileIndex.ShapeFileEnumerator..ctor(Stream stream)
   at SharpMap.Data.Providers.ShapeFileIndex.ShapeFileEnumerator..ctor(String shpPath)
   at SharpMap.Data.Providers.ShapeFileIndex.Create(String shpPath)
   at SharpMap.Data.Providers.ShapeFile..ctor(String filename, Boolean fileBasedIndex)
   at MapTest.Program.CreateWindow() in Program.cs:line 48
   at MapTest.Program.Main(String[] args) in Program.cs:line 23
```

[shapefile.zip](https://github.com/SharpMap/SharpMap/files/4867901/shapefile.zip)

**Comment by hol430** [comment]
Closing as user error ( I think it ended up being a typo in the name of the .shx file).
