### ISSUE TITLE
Re-projection issues

### ISSUE THREAD

**Issue by dimales** [SharpMap/SharpMap#232]
I have a shapefile layer in WGS 84 coordinate system, and want to re-project it to some other CS, for example North Pole Stereographic (ESRI:102018) or North Pole Lambert Azimuthal Equal Area (ESRI:102017).
I use the following code, where I set up source CS (scs) and create target CS (tcs) from WKT. 

```
ProjNet.CoordinateSystems.CoordinateSystemFactory cFac = new ProjNet.CoordinateSystems.CoordinateSystemFactory();
GeoAPI.CoordinateSystems.IGeographicCoordinateSystem scs = ProjNet.CoordinateSystems.GeographicCoordinateSystem.WGS84;
GeoAPI.CoordinateSystems.ICoordinateSystem tcs = cFac.CreateFromWkt("PROJCS[\"North_Pole_Stereographic\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"WGS_1984\",SPHEROID[\"WGS_1984\",6378137,298.257223563]],PRIMEM[\"Greenwich\",0],UNIT[\"Degree\",0.017453292519943295]],PROJECTION[\"Stereographic\"],PARAMETER[\"False_Easting\",0],PARAMETER[\"False_Northing\",0],PARAMETER[\"Central_Meridian\",0],PARAMETER[\"Scale_Factor\",1],PARAMETER[\"Latitude_Of_Origin\",90],UNIT[\"Meter\",1],AUTHORITY[\"EPSG\",\"102018\"]]");
wrld.CoordinateTransformation = new ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory().CreateFromCoordinateSystems(scs, tcs);        
```    

But when it comes to CoordinateTransformation, I get an error _System.NotSupportedException: Projection Stereographic is not supported._ What am I doing wrong?

**Comment by FObermaier** [comment]
You are using the wrong projection library. ProjNet4GeoAPI does not support [`Stereographic`](https://github.com/NetTopologySuite/ProjNet4GeoAPI/tree/v1/develop#projection-types-currently-supported) projection.

You might have more success when you use the [`SharpMap.CoordinateSystems.DotSpatial`](https://www.nuget.org/packages/SharpMap.CoordinateSystems.DotSpatial/) nuget package instead.

**Comment by dimales** [comment]
> 

I downloaded SharpMap.CoordinateSystems.DotSpatial lib, and modified the factories this way:
```
var cFac = new SharpMap.CoordinateSystems.DotSpatialCoordinateSystemFactory();
var ctFac = new SharpMap.CoordinateSystems.Transformations.DotSpatialCoordinateTransformationFactory();
```
Then tried to make some re-projections: North Pole Lambert Azimuthal Equal Area (ESRI:102017), WGS 84 / Arctic Polar Stereographic (EPSG:3995) and North Pole Stereographic (ESRI:102018) - by the way, DotSpatial doesn't read WKT in ESRI WKT format; but does in OGC WKT. With each projections I got blank map, with nothing rendered except for background colour:
![map](https://user-images.githubusercontent.com/44398125/164052220-00b808ba-ac81-4286-ba35-3b3473202571.png)

Just to be clear, this is what I get using ProjNet4GeoAPI with no reprojection of a shapefile:
![map](https://user-images.githubusercontent.com/44398125/164052592-9fc6e443-8f1f-424b-b036-7203296624c6.png)
... and with following re-projection sequence (pre-defined Mercator):
```
var ctFac = new ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory();
var scs = ProjNet.CoordinateSystems.GeographicCoordinateSystem.WGS84;
var tcs = ProjNet.CoordinateSystems.ProjectedCoordinateSystem.WebMercator;
wrld.CoordinateTransformation = ctFac.CreateFromCoordinateSystems(scs, tcs);
```   
![map1](https://user-images.githubusercontent.com/44398125/164052880-93ad8c35-16bf-460e-8d17-8b6ba7cec616.png)

**Comment by FObermaier** [comment]
I assume the reason you are seeing a blank map is because the extent of the map cannot be computed correctly when using stereographic projection on whole earth. (Env[-208441536.09145236 : -5.4498845842706164E-10, 711735.40642332763 : 2.0624726013033927E+23])

Can you try to use `map.ZoomToBox(<meaningfulExtent>)`

**Comment by dimales** [comment]
> Can you try to use `map.ZoomToExtent(<meaningfulExtent>)`

Well, just before rendering the map I have the following part:
```
SharpMap.Map myMap = new SharpMap.Map(new Size(4000, 2000));
myMap.Layers.Add(wrld);
myMap.ZoomToExtents();
```

But `.ZoomToExtents()` does not take arguments, and there is no such method `.ZoomToExtent()`...


By the way, when I have **the same shapefile re-projected in QGis manually beforehand** and then open and render it in ProjNet4GeoAPI (without applying re-projection in ProjNet4GeoAPI ), it works quite good:
![map](https://user-images.githubusercontent.com/44398125/164206481-8c2be778-ea8c-485c-bb28-9b52f4769d69.png)

**Comment by FObermaier** [comment]
I must admit that there is an issue with reprojecting the extent to _North Pole Stereographic_. This has been addressed by 0421e3c10cdd82a1dae8818f778f4c7a82598441.

The issue you are seeing in regard to _DotSpatial doesn't read WKT in ESRI WKT format_ is due to the fact that the input WKT lacks _AUTHORITY[issuer, code]_ information. This has been addressed with 1d0f0efc56a9c1f0478eaa3f1306877dcbfff32e
![ne_10m_land](https://user-images.githubusercontent.com/2065346/164425202-990f3c7e-4d8d-46bb-9ff1-1b9e9cb143d0.png)

Nevertheless, reprojecting the shapefile beforehand is a good solution.

**Comment by dimales** [comment]
> Nevertheless, reprojecting the shapefile beforehand is a good solution.

Yes, it is, but unfortunately, I have to have an opportunity to apply re-projection inside my app (different kind of them with different parameters). 
Still, I don't quite understood, is there a way to make a good-looking re-projection (especially those aiming the North Pole) with SharpMap (ProjNet4GeoAPI or DotSpatial or anything else)? Like the one you presented - was it pre-reprojected manually, or how did you get that?

**Comment by FObermaier** [comment]
The above image was created using the current SharpMap codebase and the following code:
```C#
var css = new SharpMap.CoordinateSystems.CoordinateSystemServices(
    new SharpMap.CoordinateSystems.DotSpatialCoordinateSystemFactory(),
    new SharpMap.CoordinateSystems.Transformations.DotSpatialCoordinateTransformationFactory(),
    SharpMap.Converters.WellKnownText.SpatialReference.GetAllReferenceSystems());

SharpMap.Session.Instance.SetGeometryServices(NetTopologySuite.NtsGeometryServices.Instance)
    .SetCoordinateSystemServices(css);

var pi = DotSpatial.Projections.ProjectionInfo.FromEsriString("PROJCS[\"North_Pole_Stereographic\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"WGS_1984\",SPHEROID[\"WGS_1984\",6378137,298.257223563]],PRIMEM[\"Greenwich\",0],UNIT[\"Degree\",0.017453292519943295]],PROJECTION[\"Stereographic\"],PARAMETER[\"False_Easting\",0],PARAMETER[\"False_Northing\",0],PARAMETER[\"Central_Meridian\",0],PARAMETER[\"Scale_Factor\",1],PARAMETER[\"Latitude_Of_Origin\",90],UNIT[\"Meter\",1],AUTHORITY[\"EPSG\",\"102018\"]]");
pi.Authority = "ESRI";
pi.AuthorityCode = 102018;

var nps = new SharpMap.CoordinateSystems.DotSpatialCoordinateSystem(pi);
css.AddCoordinateSystem(102018, nps);

var map = new SharpMap.Map(new System.Drawing.Size(640, 640));
map.SRID = 102018;
            
var ds = new SharpMap.Data.Providers.ShapeFile(@"ne_10m_land_0-90.shp");
ds.SRID = 4326;

var l = new SharpMap.Layers.VectorLayer("ne_10m_land", ds);
l.TargetSRID = 102018;
l.Style.Outline = (System.Drawing.Pen)System.Drawing.Pens.Red.Clone();
l.Style.EnableOutline = true;
l.Style.Fill = (System.Drawing.Brush)System.Drawing.Brushes.AliceBlue.Clone();

map.Layers.Add(l);
map.ZoomToBox(new Envelope(-3500000, 3500000, -3500000, 3500000));
map.BackColor = System.Drawing.Color.White;

using (var img = map.GetMap())
{
    img.Save(@"ne_10m_land_0-90.png", System.Drawing.Imaging.ImageFormat.Png);
}
```

**Comment by dimales** [comment]
> The above image was created using the current SharpMap codebase and the following code:

Whoa, this is something different from what I was trying to do. What I was doing was completely wrong, Going to try this as soon as possible. 
I'm really sorry for me asking all these questions, but I truly need to know, and you seem to be only one now, who could help me! **So huge, HUGE thanks for all your help!**

In the meantime, could you please describe in a couple of words, what are all these for?
```
var css = new SharpMap.CoordinateSystems.CoordinateSystemServices(
    new SharpMap.CoordinateSystems.DotSpatialCoordinateSystemFactory(),
    new SharpMap.CoordinateSystems.Transformations.DotSpatialCoordinateTransformationFactory(),
    SharpMap.Converters.WellKnownText.SpatialReference.GetAllReferenceSystems());

SharpMap.Session.Instance.SetGeometryServices(NetTopologySuite.NtsGeometryServices.Instance)
    .SetCoordinateSystemServices(css);
```

In my example, I didn't specify following fields: `pi.Authority = "ESRI"; pi.AuthorityCode = 102018; map.SRID = 102018; ds.SRID = 4326; l.TargetSRID = 102018;` Maybe this was the problem in my case? Why exactly you had to specify these?

And I don't quite understand where in your code the actual re-projection process takes place?

In your example, as far as I understand, you just crop the imagery while rendering the map so that the final picture shows the North Pole region zoomed: `map.ZoomToBox(new Envelope(-3500000, 3500000, -3500000, 3500000));`. I also don't need the whole globe in the map. Thus, the question: do I always have to work with full globe shapefile and then crop the image and zoom to content while rendering it, **OR** is there a way I could crop the shapefile during the re-projection process (maybe by giving some parameters?) - like, cropping out certain sector of a globe (Greenland, for example), applying rotation - with keeping the geo-spatial meta-info?

And, in general, whithout asking for help, I could never end up in really making reprojection. Is there any info/guide for SharpMap, that could help in getting this knowledge?

**Comment by FObermaier** [comment]
SharpMap relies on 3rd party libraries for reprojection, currently ProjNet4GeoAPI or DotSpatial.Projections.
The initial code block sets up SharpMap to use DotSpatial.Projections library.

The reprojection is invoked using [`SharpMap.Layers.Layer.ToSource(Geometry)`](https://github.com/SharpMap/SharpMap/blob/1d0f0efc56a9c1f0478eaa3f1306877dcbfff32e/SharpMap/Layers/Layer.cs#L649-L674) or [`SharpMap.Layers.Layer.ToTarget(Geometry)`](https://github.com/SharpMap/SharpMap/blob/1d0f0efc56a9c1f0478eaa3f1306877dcbfff32e/SharpMap/Layers/Layer.cs#L631-L647)

Setting the SRID and TargetSRID values is not necessary but in that case you would have to set SharpMap.Layer.CoordinateTransformation and SharpMap.Layer.ReverseCoordinateTransformation yourself.

You can clip the viewport to any portion you like. SharpMap only renders the geometries that intersect with you viewport. In your special case Antarktica will cause a problem, so it is better to limit the dataset to geometries you actually need.

**Comment by dimales** [comment]
Thank  you! 
This means, _Authority, AuthorityCode_ and all the _SRIDs_ are predefined in the library, and by providing these values we letting the library know which certain CRSs we work with? And, theoretically, if I want to use projection, that is not predefined in the library, I then need to 

> set SharpMap.Layer.CoordinateTransformation and SharpMap.Layer.ReverseCoordinateTransformation yourself

?

In the example you provided I encountered unexpected error in 
`var ds = new SharpMap.Data.Providers.ShapeFile("D:\\shps\\NP\\GSHHS_l_L1.shp");`
with the following stack:
_Unhandled Exception: System.NullReferenceException: Object reference does not point to an instance of an object.
    at SharpMap.Data.Providers.ShapeFile.ParseProjection()
    at SharpMap.Data.Providers.ShapeFile..ctor(String filename, Boolean fileBasedIndex)
    at SharpMap.Data.Providers.ShapeFile..ctor(String filename)_

What could be wrong with opening the shapefile? Maybe it cannot find .prj file (which lies together with .shp)?

**Comment by FObermaier** [comment]
The prj file is lacking an `AUTHORITY[<issuer>, <issuerCode>]` entry.

**Comment by dimales** [comment]
Yes, it works! Thank you very much!!! The latest issue was due to the .prj file containig WKT in ESRI format. I just changed it to OGC WKT and done!
And I also figured out how to rotate and center the view during reprojection (it is done in WKT string).
![mapProjected](https://user-images.githubusercontent.com/44398125/164764512-6a864e8a-5b30-4137-b066-e23c19937187.png)
As you can see though, the map is missing some details - some certain terrain details (like, Greenland, Iceland, Svalbard archipelago and many more - all the islands). While, when I open the same shapefile in QGis these details are pretty much there. How do you think, what is behind such weird behavior?
![image](https://user-images.githubusercontent.com/44398125/164765092-cf7b0dd6-ffdb-40b8-bbb7-0205378b558e.png)
The folder where the shapefile is located also contains following files:
![image](https://user-images.githubusercontent.com/44398125/164765257-a12651de-a2bd-40ef-938a-1317842d3128.png)

I understood, that the re-projection process (invoked by `SharpMap.Layers.Layer.ToSource(Geometry)` or `SharpMap.Layers.Layer.ToTarget(Geometry)`) in your code sample is going on somewhere internally, but where exactly, explicitly is - still can't figure out... I want to render map without reprojection to see whether islands disappear or not, but can't find the command to comment it out.

**Comment by FObermaier** [comment]
Did you compile the codebase yourself?

**Comment by dimales** [comment]
> Did you compile the codebase yourself?

For a clear test project, I've taken your code sample, providing my shapefile and target projection parameters.
I'm sorry, I may not quite understand what you mean by compiling the codebase...

**Comment by FObermaier** [comment]
But you used the Nuget packages? You need to compile the SharpMap Solution yourself and use that. As I mentioned earlier, there is a problem with reprojecting the extent to and from _North Pole Stereographic_

**Comment by dimales** [comment]
> But you used the Nuget packages? You need to compile the SharpMap Solution yourself and use that. As I mentioned earlier, there is a problem with reprojecting the extent to and from _North Pole Stereographic_

Oh, I see, you meant making modifications to the SharpMap lib itself, its source code! Yes, I'm going to find out how, and do it ASAP, thank you!

**Comment by dimales** [comment]
> You need to compile the SharpMap Solution yourself and use that.

Okay, so I did the following steps:
   - Opened Visual Studio and cloned the SharpMap lib from Github to open as a new project;
   - Made sure that it already has [fix]https://github.com/SharpMap/SharpMap/commit/0421e3c10cdd82a1dae8818f778f4c7a82598441);
   - Built solution.

 Then I made an attempt to create my map:
   - Created new C# project;
   - To be sure everything works right, I installed all the necessary libs (except for SharpMap) via "Manage Nuget packages" - the packeges are Common.Logging, Common.Logging.Core, DotSpatial.Projections, GeoApi, GeoApi.CoordinateSystems, NetTopologySuite, ProjNET, System.Drawing.Common, System.Drawing.Primitives;
   - To those packages I then added the link for the **SharpMap** (\SharpMap\bin\Debug\netstandard2.0\SharpMap.dll) and **SharpMap.CoordinateSystems.DotSpatial** (\SharpMap.CoordinateSystems.DotSpatial\obj\Debug\net472\SharpMap.CoordinateSystems.DotSpatial.dll), which I previously bulit.
All errors of missing packages gone and I tried rendering the map. The result...:
![mapProjected](https://user-images.githubusercontent.com/44398125/165571528-6fc22e96-86dc-42ef-a7c5-dd369229b161.png)
I'm sure I did something wrong. Could you please assist me with that?

**UPDATE**: Oh no, I did it!!! I had just added link to the wrong **SharpMap** and **SharpMap.CoordinateSystems.DotSpatial**! When I rebuilt the SharpMap libs, all the necessary .dll's were put into \UnitTests\bin\Debug\net472 folder! I tried those instances and everything worked out!
![mapProjected](https://user-images.githubusercontent.com/44398125/165585006-62155af9-1317-4fe8-b873-744fcdd3490f.png)
It works! All thanks to you, I'm so very greatful!
Now I'm going to play a bit with different projections, parameters, and then move further to drawing some real data on top of the map.
