### ISSUE TITLE
Race condition causing exception in Map

### ISSUE THREAD

**Issue by skazemi** [SharpMap/SharpMap#76]
I get the following exception in Map.cs:

> 'System.InvalidOperationException'  {"Object is currently in use elsewhere."}

StackTrace:
   at System.Drawing.Drawing2D.Matrix.get_IsIdentity()
   at SharpMap.Map.WorldToImage(Coordinate p, Boolean careAboutMapTransform) in SharpMap\Map\Map.cs:line 1047
   at SharpMap.Map.get_Envelope() in SharpMap\Map\Map.cs:line 1153

**Comment by skazemi** [comment]
Resolved race condition on Map.MapTransform #94
